language: java

jdk:
- oraclejdk8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y unzip

install:
  - wget https://github.com/thetangram/triangle/archive/master.zip
  - unzip master.zip -d .
  - mvn -f ./triangle-master/pom.xml clean install
  - rm -rf ./triangle-master

