info:
  component: Triangle Web Composer

server:
  port: 8080
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
  metrics:
    enabled: true
  env:
    enabled: true

zuul.debug.request: true

zuul:
  ignoredPatterns: /health,/routes,/trace,/metrics,/env
  routes:
    header:
      path: "/header/index.html"
      stripPrefix: false
      serviceId: components
    footer:
      path: "/footer/index.html"
      stripPrefix: false
      serviceId: components
    nav:
      path: "/nav/index.html"
      stripPrefix: false
      serviceId: components
    test:
      path: "/test/index.html"
      stripPrefix: false
      serviceId: components

components:
  ribbon:
    listOfServers: localhost:9000
    
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 100000

logging:
  level:
    ROOT: INFO
    net.acesinc: DEBUG
    org.apache.http.headers: DEBUG
